// http://www.graphviz.org/content/cluster

digraph G {

    subgraph cluster_main{
    style=filled;
    color=lightgrey;
    node [style=filled,color=white];
        label = "referer";
        "google.co.jp"; "webfood.info"; "direct"; "mail.yahoo.co.jp";
    }

    subgraph cluster_info{
        node [style=filled]
        "/privacypolicy";"/term";"/warning";"/teaching";
        style=filled;
        color=hotpink1;
        label="info_page";
    }

  subgraph cluster_mugcup{
      node [style=filled];
      "/mugcups"; "/mugcups/0"; "/mugcups/1"; "/mugcups/2"; "/mugcups/3"; "/mugcups/4"; "/mugcups/5"; "/mugcups/6"; "/mugcups/7"; "/mugcups/8"; "/mugcups/9"; "/mugcups/10"; "/mugcups/11";
      label = "mugcups";
      style=filled;
      color=dodgerblue;
  }

  subgraph cluster_coffee_cup{
      node [style=filled];
      "/coffee_cups"; "/coffee_cups/1"; "/coffee_cups/2"; "/coffee_cups/3"; "/coffee_cups/4";
      "/coffee_cups/5"; "/coffee_cups/6"; "/coffee_cups/7"; "/coffee_cups/8";
      label = "coffee_cups";
      style=filled;
      color = firebrick1;
  }

  subgraph cluster_code{
      node [style=filled];
      "/codes"; "/codes/4"; "/codes/5"; "/codes/6"; "/codes/7"; "/codes/8"; "/codes/9"; "/codes/10"; "/codes/11";
      "/codes/c_1"; "/codes/c_2";"/codes/c_3";"/codes/c_4";"/codes/c_5";"/codes/c_7";
      label = "codes"
      style=filled;
      color=limegreen;
  }

  subgraph cluster_setting{
      node [style=filled]
      "/mugcups/how_to_save"; "/mugcups/how_to_open";"/mugcups/html_tags";"/mugcups/css";
      "/mugcups/windows_rails";"/mugcups/windows_tips";"/mugcups/heroku";
      label = "settings";
      style=filled;
      color=khaki1;
  }

"webfood.info"->"/"
"/"->"/mugcups"
"/mugcups"->"/mugcups/9"
"/mugcups"->"/mugcups/9"
"/"->"/warning"
"/warning"->"/"
"/"->"/warning"
"/"->"/teaching"
"/teaching"->"/warning"
"/warning"->"/warning"
"/warning"->"/codes"
"/warning"->"/codes"
"/codes"->"/mugcups/html_tags"
"/mugcups/html_tags"->"/codes"
"/codes"->"/mugcups/how_to_save"
"/codes"->"/mugcups/how_to_open"
"/codes"->"/mugcups/html_tags"
"/mugcups/html_tags"->"/mugcups/7"
"/mugcups/7"->"/mugcups/6"
"/mugcups/7"->"/mugcups/6"
"/mugcups/7"->"/mugcups"
"/mugcups"->"/mugcups/0"
"/mugcups/0"->"/mugcups/1"
"/mugcups/0"->"/mugcups/1"
"/mugcups/1"->"/mugcups/2"
"/mugcups/7"->"/mugcups"
"/mugcups/2"->"/mugcups/3"
"direct"->"/"
"/"->"/mugcups"
"/mugcups"->"/mugcups/2"
"/"->"/mugcups"
"/mugcups"->"/mugcups/2"
"/mugcups/2"->"/mugcups/3"
"/mugcups/2"->"/mugcups/3"
"/mugcups/3"->"/mugcups/html_tags"
"/mugcups/3"->"/mugcups/css"
"/mugcups/3"->"/mugcups/2"
"/mugcups/3"->"/mugcups/4"
"/mugcups/3"->"/mugcups/4"
"/mugcups/3"->"/mugcups/4"
"/mugcups/html_tags"->"/mugcups/7"
"/mugcups/css"->"/mugcups/6"
"/mugcups/css"->"/mugcups/8"
"/mugcups/css"->"/mugcups/7"
"direct"->"/mugcups"
"/mugcups/4"->"/mugcups/5"
"/mugcups/4"->"/mugcups/5"
"/mugcups/4"->"/mugcups/5"
"direct"->"/"
"/"->"/mugcups"
"/mugcups"->"/mugcups/5"
"/mugcups"->"/mugcups/7"
"/mugcups"->"/mugcups/8"
"/mugcups"->"/mugcups/9"
"/mugcups"->"/mugcups/10"
"/mugcups"->"/mugcups/11"
"/mugcups"->"/mugcups/4"
"/"->"/mugcups"
"/mugcups"->"/mugcups/5"
"/mugcups/5"->"/codes/5"
"/"->"/mugcups"
"/mugcups/5"->"/codes/5"
"/mugcups/5"->"/codes/5"
"/mugcups/5"->"/codes/5"
"/mugcups/5"->"/codes/5"
"/mugcups/5"->"/mugcups/6"
"/mugcups/6"->"/mugcups/4"
"/mugcups/6"->"/codes/6"
"/"->"/mugcups"
"direct"->"/"
"/"->"/mugcups"
"/mugcups"->"/mugcups/6"
"/"->"/mugcups/6"
"/mugcups/6"->"/codes/6"
"/mugcups/6"->"/mugcups/5"
"/mugcups/6"->"/mugcups/5"
"/mugcups/6"->"/mugcups/7"
"/"->"/mugcups"
"/mugcups/7"->"/codes/7"
"/mugcups"->"/teaching"
"/mugcups/7"->"/mugcups/7"
"/mugcups/7"->"/mugcups/7"
"/mugcups/7"->"/codes/7"
"/mugcups/7"->"/mugcups/8"
"/"->"/mugcups"
"/mugcups"->"/mugcups/7"
"direct"->"/"
"/"->"/mugcups"
"/mugcups"->"/mugcups/8"
"/mugcups/8"->"/codes/8"
"/mugcups/8"->"/mugcups/9"
"/mugcups/9"->"/mugcups/4"
"/"->"/mugcups"
"/mugcups/9"->"/mugcups/7"
"/mugcups/9"->"/codes/9"
"/mugcups/9"->"/codes/9"
"/mugcups/9"->"/mugcups/10"
"direct"->"/"
"/"->"/mugcups"
"/mugcups"->"/mugcups/10"
"direct"->"/"
"/"->"/mugcups"
"/mugcups"->"/mugcups/10"
"/mugcups/10"->"/codes/10"
"/mugcups/10"->"/mugcups/11"
"/mugcups/11"->"/mugcups/4"
"/mugcups/11"->"/mugcups/4"
"/"->"/mugcups"
"/mugcups"->"/mugcups/11"
"/mugcups/11"->"/codes/5"
"/mugcups/11"->"/mugcups/5"
"/mugcups/11"->"/codes/11"
"/mugcups/11"->"/coffee_cups/8"
"/mugcups/11"->"/mugcups/heroku"
"/mugcups/11"->"/codes/11"
"/"->"/coffee_cups"
"/coffee_cups"->"/coffee_cups/1"
"/coffee_cups/1"->"/mugcups/3"
"/"->"/coffee_cups"
"/coffee_cups"->"/coffee_cups"
"/"->"/mugcups"
"direct"->"/mugcups"
"/mugcups"->"/codes"
"/codes"->"/codes/10"
"/codes"->"/codes/11"
"/mugcups"->"/codes"
"/codes"->"/codes/9"
"/codes"->"/codes/9"
"/codes"->"/codes/10"
"/codes"->"/codes/11"
"/codes"->"/codes/11"
"direct"->"/mugcups"
"/mugcups"->"/mugcups/0"
"/mugcups/0"->"/mugcups/1"
"/mugcups/1"->"/mugcups/2"
"/mugcups/2"->"/mugcups/3"
"/mugcups/3"->"/mugcups/2"
"direct"->"/mugcups/2"
"direct"->"/"
"/mugcups/2"->"/mugcups/2"
"/"->"/"
"/mugcups/2"->"/mugcups/3"
"direct"->"/"
"/"->"/mugcups"
"/mugcups"->"/mugcups/0"
"/mugcups/0"->"/mugcups/1"
"/mugcups/1"->"/mugcups/2"
"/mugcups/2"->"/mugcups/3"
"/mugcups/3"->"/mugcups/html_tags"
"/mugcups/3"->"/mugcups/4"
"direct"->"/"
"/"->"/mugcups"
"/"->"/mugcups"
"/"->"/mugcups/4"
"/mugcups"->"/mugcups"
"/mugcups/4"->"/mugcups/4"
"/"->"/mugcups"
"/"->"/mugcups/4"
"/mugcups/4"->"/mugcups/4"
"/mugcups"->"/mugcups"
"/mugcups/4"->"/mugcups/5"
"direct"->"/"
"/"->"/mugcups"
"/mugcups"->"/mugcups/5"
"/mugcups"->"/mugcups/5"
"/mugcups/5"->"/mugcups/6"
"/"->"/mugcups"
"/mugcups/6"->"/mugcups/7"
"/mugcups/6"->"/mugcups/7"
"direct"->"/"
"/"->"/mugcups"
"/mugcups"->"/mugcups/6"
"/mugcups/6"->"/mugcups/5"
"/"->"/mugcups"
"/mugcups"->"/mugcups"
"direct"->"/mugcups/7"
"/"->"/mugcups"
"direct"->"/"
"/mugcups/7"->"/mugcups/7"
"/mugcups"->"/mugcups"
"/"->"/"
"direct"->"/"
"/"->"/mugcups"
"/"->"/mugcups"
"/mugcups"->"/mugcups/7"
"/mugcups"->"/mugcups/8"
"/mugcups/7"->"/mugcups/8"
"/mugcups/8"->"/mugcups/6"
"/mugcups/6"->"/mugcups/5"
"/mugcups/6"->"/mugcups/5"
"/mugcups/8"->"/mugcups/9"
"/mugcups/9"->"/coffee_cups"
"/mugcups"->"/mugcups/9"
"/mugcups"->"/mugcups/9"
"direct"->"/"
"/"->"/mugcups"
"/mugcups"->"/mugcups/9"
"/"->"/mugcups"
"/mugcups/9"->"/mugcups/10"
"direct"->"/"
"direct"->"/"
"/"->"/mugcups"
"/"->"/mugcups"
"/mugcups"->"/mugcups/10"
"direct"->"/mugcups/9"
"/mugcups/10"->"/mugcups/11"
"/mugcups/11"->"/mugcups"
"/mugcups"->"/mugcups/10"
"/mugcups"->"/mugcups/10"
"direct"->"/"
"/"->"/mugcups"
"/mugcups"->"/mugcups/11"
"direct"->"/coffee_cups/8"
"direct"->"/mugcups/heroku"
"/"->"/coffee_cups"
"/coffee_cups/8"->"/"
"/"->"/mugcups"
"/mugcups"->"/mugcups/11"
"/"->"/mugcups"
"/mugcups"->"/mugcups/11"
"mail.yahoo.co.jp"->"/mugcups/10"
"mail.yahoo.co.jp"->"/mugcups/10"
"mail.yahoo.co.jp"->"/mugcups/10"
"/coffee_cups"->"/coffee_cups/1"
"/coffee_cups"->"/coffee_cups/2"
"/coffee_cups"->"/coffee_cups/8"
"/coffee_cups"->"/coffee_cups/6"
"/coffee_cups"->"/coffee_cups/1"
"direct"->"/"
"/"->"/coffee_cups"
"/coffee_cups"->"/coffee_cups/1"
"/coffee_cups/1"->"/mugcups/windows_tips"
"/"->"/coffee_cups"
"direct"->"/mugcups/10"
"/coffee_cups/1"->"/coffee_cups/2"
"direct"->"/"
"/"->"/coffee_cups"
"/coffee_cups"->"/coffee_cups/1"
"/"->"/coffee_cups"
"/coffee_cups/1"->"/coffee_cups/2"
"direct"->"/mugcups/4"
"direct"->"/"
"direct"->"/mugcups/6"
"/coffee_cups/2"->"/coffee_cups/3"
"/coffee_cups"->"/mugcups"
"/mugcups"->"/mugcups/2"
"direct"->"/"
"/"->"/coffee_cups"
"direct"->"/coffee_cups/3"
"/coffee_cups"->"/mugcups"
"/coffee_cups"->"/coffee_cups/4"
"/coffee_cups"->"/coffee_cups/3"
"direct"->"/coffee_cups/3"
"/coffee_cups/3"->"/coffee_cups/4"
"/"->"/coffee_cups"
"/coffee_cups"->"/coffee_cups/5"
"/"->"/coffee_cups"
"direct"->"/coffee_cups/4"
"direct"->"/"
"/"->"/"
"/coffee_cups"->"/coffee_cups"
"/coffee_cups/4"->"/coffee_cups/4"
"direct"->"/"
"direct"->"/coffee_cups/3"
"direct"->"/coffee_cups/3"
"/coffee_cups/3"->"/coffee_cups/3"
"/coffee_cups/3"->"/coffee_cups/3"
"/"->"/"
"/coffee_cups/3"->"/coffee_cups/4"
"direct"->"/"
"/"->"/coffee_cups"
"/coffee_cups"->"/coffee_cups/4"
"/"->"/coffee_cups"
"direct"->"/"
"direct"->"/"
"/"->"/coffee_cups"
"/coffee_cups"->"/coffee_cups/4"
"/coffee_cups/4"->"/coffee_cups/3"
"/"->"/coffee_cups"
"direct"->"/"
"/"->"/coffee_cups"
"/coffee_cups"->"/coffee_cups/1"
"direct"->"/"
"/"->"/coffee_cups"
"/coffee_cups/1"->"/mugcups/8"
"/coffee_cups/1"->"/mugcups/7"
"/coffee_cups/1"->"/mugcups/10"
"/coffee_cups/1"->"/coffee_cups/2"
"/"->"/coffee_cups"
"direct"->"/"
"/"->"/coffee_cups/2"
"/coffee_cups"->"/coffee_cups"
"/coffee_cups/2"->"/coffee_cups/2"
"/"->"/"
"/"->"/coffee_cups/2"
"/coffee_cups/2"->"/mugcups/4"
"direct"->"/mugcups/6"
"/coffee_cups"->"/coffee_cups/3"
"direct"->"/"
"/"->"/coffee_cups"
"/coffee_cups"->"/coffee_cups/3"
"/"->"/coffee_cups"
"/coffee_cups"->"/coffee_cups/3"
"/coffee_cups/3"->"/coffee_cups/4"
"/coffee_cups/3"->"/coffee_cups"

}
